### ISSUE TITLE
Hi, is the license for this project friendly?

### ISSUE THREAD

**Issue by zhengxs2018** [danprince/zrpc#1]
Hi,

I found the code for this project to be quite interesting and clean. I would like to refer to it and abstract a language-model call for an open-source project.

My project uses [h3](https://github.com/unjs/h3) + [Zod](https://github.com/colinhacks/zod) for lightweight JSON-RPC, though it doesn’t need to be as generic as [tRPC](https://trpc.io/).

However, I noticed that there is no license information provided for this project. Understanding the licensing terms is important to me, as I want to ensure that I am respecting the authors’ intentions and adhering to legal requirements.

Could you please clarify the license under which this project is released?

Thank you!

The target project: [auto-dev-vscode](https://github.com/unit-mesh/auto-dev-vscode)

**Comment by danprince** [comment]
Hey @zhengxs2018, I'm glad it was interesting to you. This was just a hobby project and you're welcome to reference/fork/reuse any of it. I've added the Unlicense to clarify: https://github.com/danprince/zrpc/commit/280e41a7e90cbbedd9d88dc1368a20fae84b8647.

**Comment by zhengxs2018** [comment]
Thank you for your reply. This is a great project.
